# Generated by Django 4.1.2 on 2022-10-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="person",
            name="image2",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
